CREATE DATABASE lanchonete_07_04
GO

USE lanchonete_07_04

CREATE TABLE categorias (
	codigo	INT			NOT NULL PRIMARY KEY IDENTITY,
	nome	VARCHAR(50) NOT NULL
);
GO

CREATE TABLE lanches (
	codigo				INT				NOT NULL PRIMARY KEY IDENTITY,
	nome				VARCHAR(50)		NOT NULL,
	preco				DECIMAL(10,2)	NOT NULL,
	calorias			INT				NOT NULL,
	categoria_codigo	INT				NOT NULL REFERENCES CATEGORIAS
);
GO

CREATE TABLE bebidas (
	codigo	INT				NOT NULL PRIMARY KEY IDENTITY,
	nome	VARCHAR(50)		NOT NULL,
	preco	DECIMAL(10,2)	NOT NULL,
	estoque INT
);
GO

CREATE TABLE ufs (
	sigla	CHAR(2)			NOT NULL PRIMARY KEY,
	nome	VARCHAR(50)		NOT NULL
);
GO

CREATE TABLE cidades (
	codigo		INT				NOT NULL PRIMARY KEY IDENTITY,
	nome		VARCHAR(50)		NOT NULL,
	uf_sigla	CHAR(2)			NOT NULL REFERENCES ufs
);
GO

CREATE TABLE ceps (
	nr				VARCHAR(10)		NOT NULL PRIMARY KEY,
	cidade_codigo	INT				NOT NULL REFERENCES cidades
);
GO

CREATE TABLE pessoas (
	codigo INT NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL,
	cpf VARCHAR(15) NOT NULL UNIQUE,
	cep_nr VARCHAR(10) NOT NULL REFERENCES ceps,
	logadouro VARCHAR(100) NOT NULL,
	nr VARCHAR(5) NOT NULL 
);
GO

CREATE TABLE telefones (
	pessoas_codigo INT NOT NULL REFERENCES pessoas,
	nr VARCHAR(20) NOT NULL,
	PRIMARY KEY(pessoas_codigo, nr) -- chave primaria composta
);
GO

CREATE TABLE clientes (
	pessoas_codigo INT NOT NULL PRIMARY KEY REFERENCES pessoas,
	estrelas INT 
);
GO

CREATE TABLE funcionarios (
	pessoa_codigo INT NOT NULL PRIMARY KEY REFERENCES pessoas,
	salario DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE entregadores (
	pessoa_codigo INT NOT NULL PRIMARY KEY REFERENCES pessoas,
	valor_diaria DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE entregas (
	codigo INT NOT NULL PRIMARY KEY IDENTITY,
	data_hora_saida DATETIME NULL,
	status INT NULL,
	entregador_codigo INT NOT NULL REFERENCES entregadores
);
GO

CREATE TABLE pedidos (
	nr INT NOT NULL PRIMARY KEY IDENTITY,
	data DATETIME NOT NULL DEFAULT GETDATE(),
	total DECIMAL(10,2) NULL,
	status INT NULL,
	cliente_codigo INT NOT NULL REFERENCES clientes,
	funcionario_codigo INT NOT NULL REFERENCES funcionarios,
	entrega_codigo INT NULL REFERENCES entregas
);
GO

CREATE TABLE pedidos_lanches (
	pedido_nr INT NOT NULL REFERENCES pedidos,
	lanche_codigo INT NOT NULL REFERENCES lanches,
	qtd INT NOT NULL,
	preco DECIMAL(10,2) NOT NULL,
	PRIMARY KEY(pedido_nr, lanche_codigo)
);
GO

CREATE TABLE pedidos_bebidas (
	 pedido_nr INT NOT NULL REFERENCES pedidos,
	 bebida_codigo INT NOT NULL REFERENCES bebidas,
	 qtd INT NOT NULL,
	 PRIMARY KEY(pedido_nr, bebida_codigo)
);
GO

-----------------------------------------------------------

-- CATEGORIAS
INSERT INTO CATEGORIAS (NOME) 
VALUES ('Hamburguer'), ('Frango'), ('Filé');


-- LANCHES
INSERT INTO LANCHES (NOME, PRECO, CALORIAS, CATEGORIA_CODIGO) 
VALUES ('X-tudo', 30, 1000, 1);

INSERT INTO LANCHES (NOME, PRECO, CALORIAS, CATEGORIA_CODIGO) 
VALUES ('X-Bacon', 25, 700, 1);

INSERT INTO LANCHES (NOME, PRECO, CALORIAS, CATEGORIA_CODIGO) 
VALUES ('Peito Tudo', 27, 650, 2);

INSERT INTO LANCHES (NOME, PRECO, CALORIAS, CATEGORIA_CODIGO) 
VALUES ('X-tudo', 30, 1000, 1);


-- BEBIDAS
INSERT INTO BEBIDAS (NOME, PRECO, ESTOQUE) 
VALUES ('Coca-cola Zero Lata 350 Ml', 6, 500);

INSERT INTO BEBIDAS (NOME, PRECO, ESTOQUE) 
VALUES ('Cotubinha', 10, 50);

INSERT INTO BEBIDAS (NOME, PRECO, ESTOQUE) 
VALUES ('Long Neck Stella Ultra', 15, 50);


-- UFS
INSERT INTO UFS (SIGLA, NOME) 
VALUES ('SP', 'São Paulo'), ('MG', 'Minas Gerais');


-- CIDADES
INSERT INTO CIDADES (NOME, UF_SIGLA) 
VALUES ('São José do Rio Preto', 'SP');

INSERT INTO CIDADES (NOME, UF_SIGLA) 
VALUES ('Fronteira', 'MG');

INSERT INTO CIDADES (NOME, UF_SIGLA) 
VALUES ('Mirassol', 'SP');


-- CEPS
INSERT INTO CEPS (NR, CIDADE_CODIGO) 
VALUES ('15043-020', 1);

INSERT INTO CEPS (NR, CIDADE_CODIGO) 
VALUES ('15130-000', 3);

INSERT INTO CEPS (NR, CIDADE_CODIGO) 
VALUES ('38230-000', 2);


-- PESSOAS
INSERT INTO PESSOAS (NOME, CPF, CEP_NR, LOGADOURO, NR) 
VALUES ('Matheus Mortari', '1010', '15043-020', 'Rua Fernandópolis', '2510');

INSERT INTO PESSOAS (NOME, CPF, CEP_NR, LOGADOURO, NR) 
VALUES ('Matheus de Pau', '2020', '15130-000', 'Rua Maria de Fatima', '1000');

INSERT INTO PESSOAS (NOME, CPF, CEP_NR, LOGADOURO, NR) 
VALUES ('Pedro Linhares', '3030', '38230-000', 'Av. Minas Gerais', '150');


-- CLIENTES
INSERT INTO CLIENTES (PESSOAS_CODIGO, ESTRELAS) 
VALUES (1, 1);


-- FUNCIONARIOS
INSERT INTO FUNCIONARIOS (PESSOA_CODIGO, SALARIO) 
VALUES (2, 2000);


-- ENTREGADORES
INSERT INTO ENTREGADORES (PESSOA_CODIGO, VALOR_DIARIA) 
VALUES (3, 150);


-- ENTREGAS
INSERT INTO ENTREGAS (ENTREGADOR_CODIGO) 
VALUES (3);


-- PEDIDOS
INSERT INTO PEDIDOS (CLIENTE_CODIGO, FUNCIONARIO_CODIGO) 
VALUES (1, 2);


-- PEDIDOS_LANCHES
INSERT INTO PEDIDOS_LANCHES (PEDIDO_NR, LANCHE_CODIGO, QTD, PRECO) 
VALUES (1, 1, 3, 30);

INSERT INTO PEDIDOS_LANCHES (PEDIDO_NR, LANCHE_CODIGO, QTD, PRECO) 
VALUES (1, 3, 5, 27);

INSERT INTO PEDIDOS_LANCHES (PEDIDO_NR, LANCHE_CODIGO, QTD, PRECO) 
VALUES (1, 2, 2, 25);


-- PEDIDOS_BEBIDAS (CORRIGIDO)
INSERT INTO PEDIDOS_BEBIDAS (PEDIDO_NR, BEBIDA_CODIGO, QTD) 
VALUES (1, 2, 3);

INSERT INTO PEDIDOS_BEBIDAS (PEDIDO_NR, BEBIDA_CODIGO, QTD) 
VALUES (1, 1, 1);
