spring.application.name=demo
spring.jpa.open-in-view=true

# Configurações do banco de dados SQL Server
spring.datasource.url=jdbc:sqlserver://F121-LB5-N14;databaseName=bdtestelp2;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=aluno
spring.datasource.password=dba
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Se você também estiver servindo páginas web, pode querer configurar o filtro de codificação de caracteres
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true